#!/usr/bin/env python3
"""
Simple plotting script to visualize SMIL PCA data generated by the Blender addon.

This script creates interactive scatter plots of the first two principal components
from either entangled PCA (shape+scale+translation) or morph PCA (scale+translation) data.

Usage:
    python plot_pca_data.py <path_to_xy_data_file>

Example:
    python plot_pca_data.py 3D_model_prep/smil_entangled_PC_xy.csv
    python plot_pca_data.py 3D_model_prep/smil_morph_PC_xy.csv
"""

import sys
import os
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.offline import plot
import argparse


def load_pca_data(filepath):
    """
    Load PCA XY data from CSV file.
    
    Args:
        filepath (str): Path to the CSV file containing PCA data
        
    Returns:
        pandas.DataFrame: DataFrame with columns ['label', 'PC1', 'PC2']
    """
    if not os.path.exists(filepath):
        raise FileNotFoundError(f"File not found: {filepath}")
    
    try:
        df = pd.read_csv(filepath)
        
        # Validate required columns
        required_columns = ['label', 'PC1', 'PC2']
        if not all(col in df.columns for col in required_columns):
            raise ValueError(f"CSV file must contain columns: {required_columns}")
        
        print(f"Loaded {len(df)} data points from {filepath}")
        return df
        
    except Exception as e:
        raise ValueError(f"Error reading CSV file: {e}")


def create_interactive_plot(df, title, output_dir=None):
    """
    Create an interactive scatter plot using Plotly.
    
    Args:
        df (pandas.DataFrame): DataFrame with PCA data
        title (str): Plot title
        output_dir (str): Directory to save the plot (optional)
        
    Returns:
        str: Path to the saved HTML file
    """
    # Create the scatter plot
    fig = go.Figure()
    
    # Add scatter points with hover information
    fig.add_trace(go.Scatter(
        x=df['PC1'],
        y=df['PC2'],
        mode='markers',
        marker=dict(
            size=12,
            color='steelblue',
            line=dict(width=1, color='white')
        ),
        text=df['label'],
        hovertemplate=(
            "<b>%{text}</b><br>" +
            "PC1: %{x:.3f}<br>" +
            "PC2: %{y:.3f}<br>" +
            "<extra></extra>"
        ),
        name="PCA Data Points"
    ))
    
    # Update layout
    fig.update_layout(
        title=dict(
            text=title,
            x=0.5,
            font=dict(size=16)
        ),
        xaxis_title="PC1",
        yaxis_title="PC2",
        width=800,
        height=600,
        showlegend=False,
        hovermode='closest',
        plot_bgcolor='white'
    )
    
    # Add grid
    fig.update_xaxes(showgrid=True, gridwidth=1, gridcolor='lightgray')
    fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor='lightgray')
    
    # Generate output filename
    if output_dir is None:
        output_dir = os.path.dirname(os.path.abspath(__file__))
    
    # Determine plot type from title
    if "entangled" in title.lower():
        plot_type = "entangled"
    elif "morph" in title.lower():
        plot_type = "morph"
    else:
        plot_type = "pca"
    
    html_filename = f"smil_{plot_type}_pca_plot.html"
    svg_filename = f"smil_{plot_type}_pca_plot.svg"
    
    html_path = os.path.join(output_dir, html_filename)
    svg_path = os.path.join(output_dir, svg_filename)
    
    # Save as HTML (interactive)
    plot(fig, filename=html_path, auto_open=False)
    print(f"Interactive plot saved as: {html_path}")
    
    # Save as SVG (static, for external editing)
    fig.write_image(svg_path, format="svg", width=800, height=600)
    print(f"Static plot saved as: {svg_path}")
    
    return html_path


def create_enhanced_plot(df, title, output_dir=None):
    """
    Create an enhanced plot with species-based coloring.
    
    Args:
        df (pandas.DataFrame): DataFrame with PCA data
        title (str): Plot title
        output_dir (str): Directory to save the plot (optional)
        
    Returns:
        str: Path to the saved HTML file
    """
    # Create the scatter plot with enhanced features
    fig = go.Figure()
    
    # Extract species/group information from labels for better coloring
    # This assumes labels follow a pattern like "species_name_...obj"
    df['species'] = df['label'].str.split('_').str[:2].str.join('_')
    
    # Get unique species for color mapping
    unique_species = df['species'].unique()
    colors = px.colors.qualitative.Set3[:len(unique_species)]
    color_map = dict(zip(unique_species, colors))
    
    # Add scatter points for each species
    for species in unique_species:
        species_data = df[df['species'] == species]
        
        fig.add_trace(go.Scatter(
            x=species_data['PC1'],
            y=species_data['PC2'],
            mode='markers',
            marker=dict(
                size=12,
                color=color_map[species],
                line=dict(width=1, color='white')
            ),
            name=species,
            text=species_data['label'],
            hovertemplate=(
                "<b>%{text}</b><br>" +
                "Species: " + species + "<br>" +
                "PC1: %{x:.3f}<br>" +
                "PC2: %{y:.3f}<br>" +
                "<extra></extra>"
            )
        ))
    
    # Update layout
    fig.update_layout(
        title=dict(
            text=title,
            x=0.5,
            font=dict(size=16)
        ),
        xaxis_title="PC1",
        yaxis_title="PC2",
        width=800,
        height=600,
        showlegend=True,
        legend=dict(
            orientation="v",
            yanchor="top",
            y=1,
            xanchor="left",
            x=1.02
        ),
        hovermode='closest',
        plot_bgcolor='white'
    )
    
    # Add grid and styling
    fig.update_xaxes(showgrid=True, gridwidth=1, gridcolor='lightgray')
    fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor='lightgray')
    
    # Generate output filename
    if output_dir is None:
        output_dir = os.path.dirname(os.path.abspath(__file__))
    
    # Determine plot type from title
    if "entangled" in title.lower():
        plot_type = "entangled"
    elif "morph" in title.lower():
        plot_type = "morph"
    else:
        plot_type = "pca"
    
    html_filename = f"smil_{plot_type}_pca_enhanced.html"
    svg_filename = f"smil_{plot_type}_pca_enhanced.svg"
    
    html_path = os.path.join(output_dir, html_filename)
    svg_path = os.path.join(output_dir, svg_filename)
    
    # Save as HTML (interactive)
    plot(fig, filename=html_path, auto_open=False)
    print(f"Enhanced interactive plot saved as: {html_path}")
    
    # Save as SVG (static, for external editing)
    fig.write_image(svg_path, format="svg", width=800, height=600)
    print(f"Enhanced static plot saved as: {svg_path}")
    
    return html_path


def main():
    """Main function to handle command line arguments and create plots."""
    parser = argparse.ArgumentParser(
        description="Create interactive plots for SMIL PCA data",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python plot_pca_data.py 3D_model_prep/smil_entangled_PC_xy.csv
  python plot_pca_data.py 3D_model_prep/smil_morph_PC_xy.csv
  python plot_pca_data.py data.csv --output-dir ./plots
  python plot_pca_data.py data.csv --enhanced
        """
    )
    
    parser.add_argument(
        'filepath',
        help='Path to the CSV file containing PCA XY data'
    )
    
    parser.add_argument(
        '--output-dir', '-o',
        help='Directory to save the plots (default: same as input file)'
    )
    
    parser.add_argument(
        '--enhanced', '-e',
        action='store_true',
        help='Create enhanced plot with species-based coloring'
    )
    
    parser.add_argument(
        '--title', '-t',
        help='Custom title for the plot'
    )
    
    args = parser.parse_args()
    
    try:
        # Load the data
        df = load_pca_data(args.filepath)
        
        # Determine output directory
        if args.output_dir:
            output_dir = args.output_dir
            os.makedirs(output_dir, exist_ok=True)
        else:
            output_dir = os.path.dirname(os.path.abspath(args.filepath))
        
        # Determine plot title
        if args.title:
            title = args.title
        else:
            # Auto-generate title based on filename
            filename = os.path.basename(args.filepath)
            if "entangled" in filename:
                title = "SMIL Entangled PCA (Shape + Scale + Translation)"
            elif "morph" in filename:
                title = "SMIL Morph PCA (Scale + Translation)"
            else:
                title = "SMIL PCA Analysis"
        
        # Create plots
        if args.enhanced:
            create_enhanced_plot(df, title, output_dir)
        else:
            create_interactive_plot(df, title, output_dir)
        
        print(f"\nPlotting completed successfully!")
        print(f"Data points: {len(df)}")
        print(f"PC1 range: {df['PC1'].min():.3f} to {df['PC1'].max():.3f}")
        print(f"PC2 range: {df['PC2'].min():.3f} to {df['PC2'].max():.3f}")
        
    except Exception as e:
        print(f"Error: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
