# An example configuration file for an optimisation

stages:
  Stage_0_init: # Initialisation stage (see next stage for comments)
    # init_rot_lock locks the rotation of the body which can be useful if you know the root mesh rotations are correct
    # default scheme: 'init'
    scheme: 'init_rot_lock'
    nits: 100 # number of iterations for this stage
    lr: 0.05 # Adam optimiser learning rate

  Stage_1_default: # chosen name of stage
      scheme: 'default' # one of 'init', 'default', 'shape', 'pose', 'deform'. See README for explanation
      nits: 300 # number of iterations for this stage
      lr: 0.02 # Adam optimiser learning rate

      loss_weights: # optional, any not provided will revert to default
          w_chamfer: 1.
          w_edge: 0.8
          w_normal: 0.02
          w_laplacian: 0.01

      custom_lrs: # optional, used to provide different learning rates to certain parameters
        joint_rot: 0.002

  Stage_2_deform_coarse:
    scheme: 'deform'
    nits: 1000
    lr: 0.002

    loss_weights: # optional, any not provided will revert to default
      w_chamfer: 1.
      w_edge: 0.8
      w_normal: 0.005
      w_laplacian: 0.01
      w_thin_regions: 0.001

  Stage_3_deform_fine:
    scheme: 'deform'
    nits: 1000
    lr: 0.0005

    loss_weights: # optional, any not provided will revert to default
      w_chamfer: 0.5
      w_edge: 0.2
      w_normal: 0.002
      w_laplacian: 0.001 # enforce smoothness less, which reduces shrinkage.
      w_thin_regions: 0.001 # thin regions should be aligned by now, so we penalise their alignment less here.

# Custom arguments. These will *overwrite* any command line arguments passed into the script
args:
  results_dir: fit3d_results
  shape_family_id: -1
