# An example configuration file for an optimisation

stages:
  Stage_0_init: # Initialisation stage (see next stage for comments)
    # init_rot_lock locks the rotation of the body which can be useful if you know the root mesh rotations are correct
    # default scheme: 'init'
    scheme: 'init_rot_lock'
    nits: 100 # number of iterations for this stage
    lr: 0.05 # Adam optimiser learning rate

    loss_weights: # optional, any not provided will revert to default
            w_chamfer: 0.5
            w_sdf: 2.

  Stage_1A_default: # chosen name of stage
    scheme: 'default' # one of 'init', 'default', 'shape', 'pose', 'deform'. See README for explanation
    nits: 500 # number of iterations for this stage
    lr: 0.01 # Adam optimiser learning rate

    loss_weights: # optional, any not provided will revert to default
          w_chamfer: 1.0
          w_edge: 0.8
          w_normal: 0.02
          w_laplacian: 0.01
          w_sdf: 5.0

    custom_lrs: # optional, used to provide different learning rates to certain parameters
      joint_rot: 0.002
      log_beta_scales: 0.005

  Stage_1B_default: # chosen name of stage
      scheme: 'default' # one of 'init', 'default', 'shape', 'pose', 'deform'. See README for explanation
      nits: 500 # number of iterations for this stage
      lr: 0.01 # Adam optimiser learning rate

      loss_weights: # optional, any not provided will revert to default
          w_chamfer: 1.
          w_edge: 0.8
          w_normal: 0.02
          w_laplacian: 0.01
          w_sdf: 0.5

      custom_lrs: # optional, used to provide different learning rates to certain parameters
        joint_rot: 0.002

  Stage_2_deform_coarse:
    scheme: 'deform'
    nits: 1000
    lr: 0.002

    loss_weights: # optional, any not provided will revert to default
      w_chamfer: 1.
      w_edge: 0.8
      w_normal: 0.005
      w_laplacian: 0.01

  Stage_3_deform_fine:
    scheme: 'deform'
    nits: 1000
    lr: 0.0005

    loss_weights: # optional, any not provided will revert to default
      w_chamfer: 0.5
      w_edge: 0.2
      w_normal: 0.002
      w_laplacian: 0.001 # enforce smoothness less, which reduces shrinkage.

# Custom arguments. These will *overwrite* any command line arguments passed into the script
args:
  results_dir: fit3d_sdf_results
  shape_family_id: -1
  use_sdf: True
